grid(first try)
IBelet/layout_catalog pull request #2
Opened 2020-09-09 10:09 UTC by IBelet

- [DEMO LINK](https://IBelet.github.io/layout_catalog/)
- [TEST REPORT LINK](https://IBelet.github.io/layout_catalog/report/html_report/)

2020-09-09 10:42 UTC, IBelet commented
видалив дів контейнер, тому дуже дивно відображаються зміни в коміті

2020-09-09 12:32 UTC, AntonSkliarov approved these changes

2020-09-09 12:32 UTC, AntonSkliarov commented on src/styles/product-row.scss
> +  row-gap: 50px;
`row-gap:`-у тоже можешь задать переменную, а то `column-gap:`-у задал, а `row-gap:` грустный сидит)))

2020-09-09 12:32 UTC, AntonSkliarov commented
Всё гуд!

2020-09-10 07:33 UTC, solaryasha requested changes
Спробуй зробити `git reset` до першого коміта в гілці `grid`.
За одно з гітом потренуєшся.

2020-09-11 07:05 UTC, closed without merging